### PR TITLE
Add robot prefabs

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
Add robots: 
Screenshot from 2023-09-07 14-36-15

From the left, second row:
- Clearpath Warthog (silver) - missing textures, color missing due to our importer
- Clearpath Husky (silver) - missing textures, mesh object with colors 
- Otto 600 (silver)
- Otto 1500 (silver)

From the left, first row:
- ANYbotics ANYmal C (no sponsorship) - poor textures
- Robotnik Summit XL (silver) - poor textures
- Clearpath Jackal (silver) - missing textures, color missing due to our importer
- Robotis OP3 (**gold**) - missing textures
- MangDang Mini Pupper (brown) - missing textures, color missing due to our importer

Standing behind:
- TM Robot TM14 (silver) - missing textures

Lying in front:
- Universal Robots UR10 (no sponsorship)

### CODE REVIEW

**Comment by jhanca-robotecai** [comment]
Next steps:
1. Select robots we want to use in the future
2. Add textures

Partially solves #67

**Comment by lewandowskikacper** [comment]
After applying fixes to inertia tags in urdfs, this robot (rbvgui, with UR arm on top) was also imported and added to the level

Screenshot from 2023-09-08 15-29-54

**Comment by jhanca-robotecai** [comment]
Please keep in mind that this branch consists of multiple imported robots that are not going to be used and should be removed before merge.

**Comment by jhanca-robotecai** [comment]
Updated groupie:
Screenshot from 2023-09-11 16-14-04

**Comment by jhanca-robotecai** [comment]
Demo level with fewer robots, but important ones, added.

**Comment by jhanca-robotecai** [comment]
Updated models:
image

**Pull request closed without merging**
